version: "3.8"
services:
  sql1:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "<YourStrong@Passw0rd>"
    ports:
      - "1433:1433"
    container_name: sql1
    hostname: "sql1"
#Votre mot de passe doit suivre la stratégie de mot de passe SQL Server par défaut, sinon le conteneur ne peut pas configurer SQL Server et s’arrête de fonctionner. Par défaut, le mot de passe doit avoir au moins huit caractères appartenant à trois des quatre groupes suivants : lettres majuscules, lettres minuscules, chiffres de base 10 et symboles. Vous pouvez examiner le journal des erreurs en exécutant la commande docker logs.

# La chaîne de connexion à utiliser pour se connecter à votre base de données SQL Server à partir de votre application .NET est la suivante :
# Server=tcp:sql1,1433;Database=maBaseDeDonnees;User ID=sa;Password=<YourStrong@Passw0rd>;Encrypt=yes;TrustServerCertificate=yes;Connection Timeout=30;